ites_ac_control:
    resource: "@ItesACControlBundle/Controller/"
    type:     annotation
    prefix:   /

ites_ac_backend:
    resource: "@ItesACBackendBundle/Controller/"
    type:     annotation
    prefix:   /backend
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

