security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: 1234, roles: [ 'ROLE_USER' ] }
                    ismael: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    dany: { password: 1234, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:   ^/
            anonymous: ~
            http_basic:
                realm: "Area Privada"

    access_control:
        - { path: ^/control/, roles: ROLE_USER }
        - { path: ^/backend/, roles: ROLE_ADMIN }
