<?php

namespace ItesAC\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArduinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArduinoRepository extends EntityRepository
{
    public function findAllWithEdificio(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT ar, e FROM ItesACBackendBundle:Arduino ar
                JOIN ar.edificio e'
            )
            ->getResult();
    }
}
