<?php

namespace ItesAC\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EdificioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdificioRepository extends EntityRepository
{
    public function findAllWithPlantas(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e, p FROM ItesACBackendBundle:Edificio e
                JOIN e.plantas p'
            )
            ->getResult();
    }
    public function findByIdForAireManagement($id){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e, ac, ar FROM ItesACBackendBundle:Edificio e
                JOIN e.aires ac
                JOIN ac.arduino ar
                WHERE e.id = :id'
            )
            ->setParameter("id", $id)
            ->getResult();
    }
}
