<?php

namespace ItesAC\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlantaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantaRepository extends EntityRepository
{
    public function findAllWithEdificio(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, e FROM ItesACBackendBundle:Planta p
                JOIN p.edificio e'
            )
            ->getResult();
    }
    public function findByIdForAireManagement($id){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, ac, ar FROM ItesACBackendBundle:Planta p
                JOIN p.aires ac
                JOIN ac.arduino ar
                WHERE p.id = :id'
            )
            ->setParameter("id", $id)
            ->getOneOrNullResult();
    }
    public function findByIdWithJoinsForControl($id){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, ac, m, e, pl FROM ItesACBackendBundle:Planta p
                JOIN p.aires ac
                JOIN ac.modelo m
                JOIN p.edificio e
                JOIN e.plantas pl
                WHERE p.id = :id'
            )
            ->setParameter("id", $id)
            ->getOneOrNullResult();
    }
}
